### ISSUE TITLE
There's a weird copy of this repo?

### ISSUE THREAD

**Issue by alecmocatta** [datatrash/wasm-png#1]
The user [@bejolithic](https://github.com/bejolithic) ("Bejolithic <human@bejolithic.tech>") seems to have made a replica of this repo? It's been cleansed of attribution and relicensed, from a brief look.

See [https://github.com/nervive/wasimage](https://github.com/nervive/wasimage/tree/948f1f01304a2cc029f8fb7ed7077054b54482c5) and [https://crates.io/crates/wasimage](https://crates.io/crates/wasimage/0.1.1).

**Comment by sagacity** [comment]
Ah, you're right. No idea what's going on there, unfortunately. Thanks for letting me know (although, to be fair, I could've responded a bit earlier 😄).
